---
- name: Restart Docker
  ansible.builtin.systemd:
     state: started
     daemon_reload: true
     name: docker
     enabled: true

- name: Daemon_reload
  ansible.builtin.systemd:
     daemon_reload: true
