---
- name: Install apt tools
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present

- name: Add key for  docker  repo
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  become: true
  ansible.builtin.apt_repository:
    repo: >
      "deb [arch=amd64 trusted=yes] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable"
    state: present

- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    allow_unauthenticated: true

- name: Change apt cache policy
  ansible.builtin.command: apt-cache policy docker-ce
  changed_when: false

- name: Install packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present

- name: Install Python modules
  ansible.builtin.pip:
    name: "{{ pip_modules }}"

- name: Create Docker.d dir
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0644'
