---
- name: Add Docker CE repository
  ansible.builtin.yum_repository:
    name: docker_ce
    description: Docker CE Repository for Amazon Linux 2
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true

- name: Update cache
  ansible.builtin.yum:
    update_cache: true

- name: Install Docker and other packages
  ansible.builtin.yum:
    name: "{{ install_docker_redhat_packages }}"
    state: present
    disable_gpg_check: true

- name: Docker create config directory
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
  loop:
    - { dest: '/root/.docker/', mode: '0644', owner: 'root', group: 'root' }
    - { dest: '/var/lib/home/scp/.docker/', mode: '0744', owner: 'root', group: 'root' }

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: >
      https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0754'

- name: Install Python modules
  ansible.builtin.pip:
    name: "{{ install_docker_pip_modules_red }}"
    extra_args: --force-reinstall

- name: Create Docker.d dir
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0644'
