---
# Create user and home directory
# Create user and home directory
- name: Create user and home directory
  ansible.builtin.user:
    name: "{{ install_github_runner_runner_user }}"
    home: "/home/{{ install_github_runner_runner_user }}"
    state: present

- name: Check if GitHub actions are configured
  ansible.builtin.stat:
    path: "{{ install_github_runner_actions_runner_dir }}/config.sh"
  register: github_actions_configured

- name: Download, extract, and configure GitHub Runner
  block:
    - name: Download actions-runner package
      ansible.builtin.get_url:
        url: "{{ install_github_runner_actions_runner_url }}"
        dest: "{{ install_github_runner_actions_runner_dir }}/actions-runner-linux-x64-{{ install_github_runner_actions_runner_version }}.tar.gz"
        mode: "0644"

    - name: Extract actions-runner package
      ansible.builtin.unarchive:
        src: "{{ install_github_runner_actions_runner_dir }}/actions-runner-linux-x64-{{ install_github_runner_actions_runner_version }}.tar.gz"
        dest: "{{ install_github_runner_actions_runner_dir }}"
        remote_src: true
        creates: "{{ install_github_runner_actions_runner_dir }}/config.sh"

    - name: Run configuration
      ansible.builtin.command:
        cmd: "./config.sh --url {{ install_github_runner_github_repo_url }} --token {{ install_github_runner_github_repo_token }}"
        chdir: "{{ install_github_runner_actions_runner_dir }}"
      become_user: gitrunner
  when: not github_actions_configured.stat.exists

- name: Run script ./run.sh
  ansible.builtin.command:
    cmd: ./run.sh
    chdir: "{{ install_github_runner_actions_runner_dir }}"

# Create Systemd unit file
- name: Create Systemd unit file
  ansible.builtin.template:
    src: templates/github-runner.service.j2
    dest: /etc/systemd/system/github-runner.service
    owner: "{{ install_github_runner_runner_user }}"
    group: "{{ install_github_runner_runner_user }}"
    mode: "0644"
  notify: Reload systemd

- name: Ensure GitHubRunner is enabled
  ansible.builtin.systemd:
    name: github-runner
    enabled: true
    daemon_reload: true
