---
- name: Configure VMs
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Create user and home directory
      user:
        name: ec2-user
        createhome: yes
        shell: /bin/bash

    - name: Install PostgreSQL and Python3
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - postgresql15


    - name: Install GitHub Runner
      shell: |
        cd /home/ec2-user
        mkdir actions-runner
        cd actions-runner
        wget https://github.com/actions/runner/releases/download/v2.282.1/actions-runner-linux-x64-2.282.1.tar.gz
        tar xzf ./actions-runner-linux-x64-2.282.1.tar.gz
        rm actions-runner-linux-x64-2.282.1.tar.gz
        # ./run.sh

    - name: Create systemd unit template
      template:
        src: github_runner.service.j2
        dest: /etc/systemd/system/github_runner.service
      notify: Restart GitHub Runner

  handlers:
    - name: Restart GitHub Runner
      systemd:
        name: github_runner
        state: restarted
