---
- name: Create Systemd Unit
  hosts: all
  become: true

  vars:
    github_runner_name: "my-runner"  # Specify the GitHub Runner name

  tasks:
    - name: Create Systemd Unit
      ansible.builtin.template:
        src: "templates/github-runner.service.j2"
        dest: >
          "/etc/systemd/system
          /github-runner-{{ github_runner_name }}.service"
        mode: "0644"
      notify: Reload Systemd
