---
- name: Install and Configure Prometheus
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        system: true
        shell: /sbin/nologin

    - name: Create Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: "0644"
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download and Extract Prometheus
      ansible.builtin.get_url:
        url: >
          "https://github.com/prometheus/prometheus/releases
          /download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
        mode: "0644"
      tags:
        - configuration

    - name: Extract Prometheus archive
      ansible.builtin.unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp/"
      become: true

    - name: Move Prometheus files to /usr/local/bin
      ansible.builtin.command:
        cmd: "mv /tmp/prometheus-2.30.3.linux-amd64/prometheus /usr/local/bin/"
        creates: /usr/local/bin/prometheus
      become: true

    - name: Copy Prometheus configuration file
      ansible.builtin.copy:
        src: "prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        owner: prometheus
        group: prometheus
        mode: "0644"

    - name: Set permissions for Prometheus configuration file
      ansible.builtin.file:
        path: "/etc/prometheus/prometheus.yml"
        owner: prometheus
        group: prometheus
        mode: "0644"

    - name: Configure Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started
      become: true
