---
- name: Configure VMs
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: install_docker
      tags:
        - docker
    - role: install_github_runner
      tags:
        - github_runner
